projects:
  galleryapp:
    schemaPath: amplify/backend/api/galleryapp/build/schema.graphql
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: /graphql
        region: us-east-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
